### ISSUE TITLE
Applying PyTorch benchmark to default PyTorch best practice

### ISSUE THREAD

**Issue by flint-stone** [bytedance/byteps#317]
Hi! I'm trying to reason about performance vs. utilization running distributed training comparing byteps and default pytorch (through NCCL). And I'm wondering the best way to reproduce the same [ benchmark script](https://github.com/bytedance/byteps/blob/master/example/pytorch/benchmark_byteps.py) for default pytorch using NCCL.

What I have attempted was to modify the script and remove all BPS components and replaced them with pytorch default package (see [link](https://gist.github.com/flint-stone/77b0280c9d7203e9c2f9e488944b1a54)). And then I run the training with default pytorch launcher (e.g.,  python3 -m torch.distributed.launch --nproc_per_node=1 --nnodes=4 --node_rank=3 --master_addr=10.10.1.1 --master_port=12345 ./benchmark_baseline.py --model resnet152 --batch-size 60) on every node. 
I'm getting a suspiciously high throughput with default setting using the given benchmark script running on 4 machines with 1 GPU each (10X higher than BPS in terms of throughput). Any insights on how to apply or modify this script to the default setting?

I'm raising this question since I was able to reproduce the same comparison with [the DDP script provided](https://github.com/bytedance/byteps/blob/master/example/pytorch/train_imagenet_resnet_byteps_ddp.py) and the performance difference was not that high and the default NCCL result was consistent with my original training process. Any suggestions are appreciated.

**Comment by ymjiang** [comment]
Let me make sure if I understand the question -- You want to test the PyTorch performance using `torch.distributed`, and  you changed [this script](https://github.com/bytedance/byteps/blob/master/example/pytorch/benchmark_byteps.py) by adding the `torch.distributed` package and removing the BytePS communication.

In your code, you do `import torch.distributed as dist` but do not use it. Usually there should be `dist.all_reduce` to perform communication. So your throughput is much higher than BytePS because it is actually training without communication.

**Comment by flint-stone** [comment]
@ymjiang The dist was used in line 53 to initiate the process group but I think I came to realize the script wasn't actually using  all reduce correctly -- closing the issue.
