### ISSUE TITLE
more workers (distributed mode) perform worse than single worker (standalone mode)?

### ISSUE THREAD

**Issue by yangwenhuan** [bytedance/byteps#52]
I'm running torch resnet50 benchmark. but get the following unexpected results. 
GPUs are the same. workers are in the same LAN, but network bandwidth between worker/server/scheduler are somewhat different. is there something wrong with my experiment?

1、single worker with 4GPUs：156 img/sec per GPU。

2、2 workers with 4GPUs respectively（8 GPUs in total）：40~50 img/sec per GPU。

**Comment by ymjiang** [comment]
For most cases, the performance of distributed training is expected to be worse than those on single worker, because the network bandwidth is usually the bottleneck. I am not sure why you said the performance is "unexpected".

However, we may help you further improve the distributed performance because 40~50 img/s indeed seems low. But we need more details on your setup:
1. How many servers did you use? I assume you are still following the example in our tutorial (that uses only 1 server). If yes, then the only server could be the performance bottleneck. 
2. Did you put server and one of the workers on the same physical machine? If yes, then the server would compete the bandwidth with the worker, which decrease the performance further.
3. Finally, reading this document might be helpful to you: https://github.com/bytedance/byteps/blob/master/docs/best-practice.md.

**Comment by yangwenhuan** [comment]
@ymjiang , single worker's training speed = 4*156 img/sec, is faster than 2 workers' training speed = 8*50 img/sec. this is the expected result? In my expectation, training speed should get faster with more workers, ideally, speed may linearly scale with workers number.

my topology and bandwidth are as follow. 

![image](https://user-images.githubusercontent.com/5866456/60963280-efed8300-a342-11e9-8f5d-46b28913ecfc.png)

**Comment by ymjiang** [comment]
Thank you for the figure. In your case, the 5.4 Gbps link is the bottleneck, and that bandwidth is too low for a DNN training task (popular cloud usually offers bandwidth >= 20Gbps). This is your physical limitation and BytePS cannot help you. You can try other frameworks (e.g., Horovod) on the same testbed and you should see even worse performance.

One suggestion: Do you have another 20 Gbps physical machine as the worker? If you do, you should use that one to replace 10.0.1.26.

**Comment by yangwenhuan** [comment]
OK, thanks, I will test with a higher bandwidth, and try hvd later.

**Comment by bobzhuyb** [comment]
@yangwenhuan Please also add more servers. The requirement is that the total server bandwidth is larger than the total worker bandwidth, otherwise the performance will be proportionally slower. Say you have two workers with 25Gbps each (in total 50Gbps), but have only one 25Gbps server, you'll only get 50% performance.

**Comment by yangwenhuan** [comment]
@bobzhuy @ymjiang , environment variables of different servers are the same? no need to specify server id like DMLC_WORKER_ID?

**Comment by ymjiang** [comment]
Yes. And no need to specify DMLC_WORKER_ID for servers.
