### ISSUE TITLE
Failure in mxnet-gluon example (RDMA)

### ISSUE THREAD

**Issue by juncgu** [bytedance/byteps#54]
**Describe the bug**
I am running the [mxnet-gluon exmaple](https://github.com/bytedance/byteps/tree/master/example/mxnet-gluon). However, the server will crash **at the beginning of training (after building connections with others)**.

Experiment setup:
[bytedance-mxnet](https://github.com/bytedance/incubator-mxnet/commit/eeb0fba2eb5cf789dcba17bf3ae56d91f52a71a3), byteps (4f40347fb92d1d33ee55a0aabc0dbc58309b9a9f)
one scheduler, one worker (on the same machine); one worker with 4 GPUs (on the other macine)

**If I use TCP, then there is no error, the job can run normally**
However, if I use **RDMA** (`DMLC_ENABLE_RDMA=1`),  the server will crash:
```text
[12:03:48] src/./rdma_van.h:572: Connecting to S[8]
[12:03:49] src/./rdma_van.h:572: Connecting to S[8]
[12:03:49] src/./rdma_van.h:572: Connecting to S[8]
[12:03:49] src/van.cc:306: S[8] is connected to others
[12:03:49] src/van.cc:446: ? => 1. Meta: request=1, timestamp=1, control={ cmd=BARRIER, barrier_group=7 }. THIS IS NOT DATA MSG!
[12:03:49] src/van.cc:471: 1 => 8. Meta: request=0, timestamp=4, control={ cmd=BARRIER, barrier_group=1505746176 }. THIS IS NOT DATA MSG!
terminate called after throwing an instance of 'dmlc::Error'
  what():  [12:04:11] src/./rdma_van.h:134: Check failed: p
```
Before that, the worker should just send a data msg to the server:
```text
[12:04:11] src/./rdma_van.h:690: send push key=0, val_len=2000, val_addr=69268529152000, rkey=1909622
[12:04:11] src/van.cc:446: ? => 8. Meta: request=1, timestamp=0, app_id=0, customer_id=0, simple_app=0, push=1, head=0, key=0, data_type={ UINT64 OTHER INT32 } Body: data_size=8 data_size=2000 data_size=4
```
If I run the [regular mxnet example](https://github.com/bytedance/byteps/tree/master/example/mxnet) with RDMA, there is no error.

The error at the server side is inside [`ps-lite`](https://github.com/bytedance/ps-lite/tree/byteps):
https://github.com/bytedance/ps-lite/blob/cd02f17b39c59fced4ae4f7688e8a8cdb54a96ca/src/rdma_van.h#L134
```cpp
char *Alloc(size_t size) {
     ...
      char *p =
          reinterpret_cast<char *>(aligned_alloc(kAlignment, new_mem_size));
      CHECK(p);
```

Thank you

**Comment by ymjiang** [comment]
Thank you very much for the reports. The gluon example is added by an external contributor (thanks @haoxintong ) and we actually haven't tested it thoroughly. We will take a look at this. 

I personally have seen a similar case on gluon-RDMA before. Could you please try this: move [these lines](https://github.com/bytedance/byteps/blob/master/example/mxnet-gluon/train_mnist_byteps.py#L100-L105) behind `train_data, val_data, train_size = get_mnist_iterator()`. That is, try to init RDMA connections after the data loaders have been created.

**Comment by juncgu** [comment]
> line 69

Thank you so much, @ymjiang.
Both of the two alternatives fix the error.  
Would you mind to share any high-level reasons for the error and the two patches with me?

Additionally, I found  using the first approach ("move lines"), the training speed is 
```text
INFO:root:Epoch[2]      Speed=8897.58 samples/s Time cost=13.486814
```
however, using the second approach ("thread_pool"), the training speed is 
```text
INFO:root:Epoch[1]      Speed=3676.64 samples/s Time cost=32.638520
```
Do you have any idea about this difference?

Thank you!

**Comment by ymjiang** [comment]
Glad that both alternatives work. :)

The high level reason is that it is not safe to fork new processes from a RDMA process. Refer to this [site](https://www.rdmamojo.com/2012/05/24/ibv_fork_init/):

`In RDMA technologies, the RDMA device is aware to the virtual->physical address mapping. When a process calls the fork() function explicitly or implicitly, due to the Copy-On-Write policy of the Linux kernel, both parent and child processes virtual pages will be mapped to the same physical memory pages. When one of them (the first) will write to such a page, it will get a new physical page, with the same content. The RDMA device, which isn't aware that the virtual->physical translation was changed to that process, may try to access the old physical address (which now may even be used by other process or the kernel). Which may lead to a data corruption or even worse - a kernel panic.`

Back to your problem. The Gluon data loader uses multi-processes by default. Originally your code inits RDMA connections first. Then gluon data loader forks new processes from it, and thus the above error occurs.

The two approaches try to avoid this. The first approach ("move lines") changes the fork order to ensure that it does not fork new processes from the RDMA process. The second approach ("thread_pool") directly avoids forking processes, and uses multi-threading to replace multi-process (refer to [this](https://mxnet.incubator.apache.org/api/python/gluon/data.html#mxnet.gluon.data.DataLoader)). 

Regard to the performance difference, I think the culprit is IO. The second approach uses multi-threading, which might affect the performance compared to using multi-process.

**Comment by juncgu** [comment]
> Glad that both alternatives work. :)
> 
> The high level reason is that it is not safe to fork new processes from a RDMA process. Otherwise the behavior will be unexpected. Refer to this [site](https://www.rdmamojo.com/2012/05/24/ibv_fork_init/):
> 
> `In RDMA technologies, the RDMA device is aware to the virtual->physical address mapping. When a process calls the fork() function explicitly or implicitly, due to the Copy-On-Write policy of the Linux kernel, both parent and child processes virtual pages will be mapped to the same physical memory pages. When one of them (the first) will write to such a page, it will get a new physical page, with the same content. The RDMA device, which isn't aware that the virtual->physical translation was changed to that process, may try to access the old physical address (which now may even be used by other process or the kernel). Which may lead to a data corruption or even worse - a kernel panic.`
> 
> Back to your problem. The Gluon data loader uses multi-processes by default. Originally your code inits RDMA connections first. Then gluon data loader forks new processes from the parent (RDMA process), and thus the above error occurs.
> 
> The two approaches try to avoid this. The first approach ("move lines") changes the fork order to ensure that it does not fork new processes from the RDMA process. The second approach ("thread_pool") directly avoids forking processes, and uses multi-threading to replace multi-process (refer to [this](https://mxnet.incubator.apache.org/api/python/gluon/data.html#mxnet.gluon.data.DataLoader)).
> 
> Regard to the performance difference, I think the culprit is data-IO. The second approach uses multi-threading, which might affect the performance compared to using multi-process. Looks like it indeed hurts performance (I didn't see the difference in past, perhaps in my case data-IO was not the bottleneck).

Thanks for your detailed explanation, @ymjiang.
I am still a little bit confused about the performance difference. I will use different hardware to see whether the difference still exists or not.
> 
> Could you please create a PR to address this issue? Just use the first approach as the current workaround. We will seek a more systematic solution in the future (we tried some before, but unfortunately didn't find a satisfying solution yet...).

Yes, I will create the PR soon.

**Comment by ymjiang** [comment]
OK, looking forward to your further tests and PR. Thank you.

**Comment by ymjiang** [comment]
https://github.com/bytedance/byteps/pull/56 solves this. closing.
