### ISSUE TITLE
I can't get the results as you provided with 4 rdma machines.

### ISSUE THREAD

**Issue by MarvinLong** [bytedance/byteps#59]
The result I got as followed, I use 2 machines as worker and the other 2 as server. I run the scripts followed [Distributed Training with RDMA](https://github.com/bytedance/byteps/blob/master/docs/step-by-step-tutorial.md). I only got 2723 images / s with 16 gpus, your result is almost 5000 images / s. So what's wrong with my training?

### machines with rdma (80Gbps)
card | image per gpu / s | single card speed up ratio | caption
-|-|-|-
1 | 335.1 | 1 | single machine
2 | 309.4 | 0.923306476 | single machine
4 | 310.6 | 0.926887496 | single machine
8 | 306.6 | 0.914950761 | single machine
16 | 170.4 | 0.508 | two workers two servers

**Comment by ymjiang** [comment]
Can you please provide more details on your setup? For example, do you co-locate workers or servers, or put them all on separate machines? What is the model and batch size per gpu?

**Comment by ymjiang** [comment]
Do you observe high variation on the training speed? Or is it consistently low?

**Comment by bobzhuyb** [comment]
@MarvinLong 

There are a few things you can try. If any of the following works for you, please let us know. Though the following env may start with `MXNET`, they apply to any workers, TF/MXNet/PyTorch, because the parameter server is based on MXNet.

1. For the parameter servers, set `export MXNET_OMP_MAX_THREADS=10` if you have 16 CPU cores per server. Set `export MXNET_OMP_MAX_THREADS=4` if you only have 8 CPU cores

2. Set `export MXNET_CPU_WORKER_NTHREADS=32` . This may speed up the parameter server

3. Start more parameter server instances. For example, when you have two physical machines to run the servers, you can start 4 (`DMLC_NUM_SERVER=4`), two server instances per physical machine. This will increase the network bandwidth utilization especially when your single TCP flow cannot saturate your bandwidth.

**Comment by MarvinLong** [comment]
@bobzhuyb thank you for your repaly. 
All my rdma machines are in use for training a bert. I will try it next week.
Actually I want to use this kit for training a bert, but when I use this to test a bert_large model (vocab size if 110k)  training speed. The speed up ratio is much lower than horovod’s . I will upload my experiment results next week.

**Comment by bobzhuyb** [comment]
@MarvinLong Do you have NVLinks? If not, BytePS may not give you speed-up because it is optimized for the scenario where the network bandwidth is the bottleneck. However, with 80Gbps RDMA without NVLinks, the bottlenck is inside each machine.

If you have NVLinks, properly configured BytePS should give you significant speedup compared with Horovod, especially with 3+ workers.

**Comment by MarvinLong** [comment]
@bobzhuyb yes, I have 4 NVLinks machines with IB. As your advise I can use them as 2 workers and 2 servers.
