### ISSUE TITLE
Do servers use openmp for reduce?

### ISSUE THREAD

**Issue by yangwenhuan** [bytedance/byteps#76]

**Comment by bobzhuyb** [comment]
Yes.

**Comment by yangwenhuan** [comment]
> Yes.

@bobzhuyb , 
1. but I found by print log that CpuReducer::sum actually run on workers. 
2. subproject incubator-mxnet in server image use openmp, and server docker file seems only compile incubator-mxnet but not byteps.
![image](https://user-images.githubusercontent.com/5866456/62506727-5d9ea900-b834-11e9-89b5-8224ac332304.png)

**Comment by bobzhuyb** [comment]
@yangwenhuan CpuReducer::sum only runs on workers and has nothing to do with servers. It is used for pe-PCI-e-switch local reducing. If you know your server topology well, you can set `BYTEPS_PCIE_SWITCH_SIZE`
to use it, as explained in https://github.com/bytedance/byteps/blob/master/docs/env.md#performance-tuning.
Otherwise, by default, CpuReducer::sum is not used.

The servers only need MXNet that has been modified by us. It uses OpenMP for reducing. You don't need to compile BytePS on server nodes.
